index:
    path: /
    controller: App\Controller\DefaultController::index

game_new_game:
    path: /game/new
    controller: App\Controller\GameController::new

game_add_player:
    path: /game/add
    controller: App\Controller\GameController::addPlayer


game_start:
    path: /game/start
    controller: App\Controller\GameController::start

game_roll:
    path: /game/roll
    controller: App\Controller\GameController::roll

game_end_turn:
    path: /game/turn
    controller: App\Controller\GameController::turn
